### ISSUE TITLE
Add context menu to image preview, instead of "X" button

### ISSUE THREAD

**Issue by FRickReich** [Envoii-Technologies/dino-ui#41]

**Comment by FRickReich** [comment]
@TeamETGmbH like this?

![Image](https://github.com/Envoii-Technologies/dino-ui/assets/492726/2ee8ee3d-ce9f-4987-ab6f-29dd4dbb3754)
![Image](https://github.com/Envoii-Technologies/dino-ui/assets/492726/e6bfceb0-23d8-43e3-8ea8-faeaad71fdeb)

**Comment by TeamETGmbH** [comment]
Looks good from my side!
